"""Change marks and scores to float

Revision ID: 6e470027605b
Revises: 35abd8838e02
Create Date: 2025-01-30 18:51:13.868629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e470027605b'
down_revision = '35abd8838e02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_marks', sa.Float(), nullable=False))
        batch_op.drop_column('marks')

    with op.batch_alter_table('quiz_attempt', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempt', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marks', sa.INTEGER(), nullable=False))
        batch_op.drop_column('max_marks')

    # ### end Alembic commands ###
