"""Add title column to quiz table

Revision ID: ccf9985c8890
Revises: 6e470027605b
Create Date: 2025-03-22 18:06:00.812785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf9985c8890'
down_revision = '6e470027605b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))

    with op.batch_alter_table('quiz_attempt', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_quiz_attempt', ['user_id', 'quiz_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempt', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_quiz_attempt', type_='unique')

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
